---
title: "编译器错误 CS0156"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS0156
helpviewer_keywords:
- CS0156
ms.assetid: 32026b1b-bcd7-4464-b63f-3b38c00452a6
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: f755172711f7a09bcbdae518fdcb82aca58cad20
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs0156"></a>编译器错误 CS0156
在嵌套在最近的封闭 catch 子句内部的 finally 子句内不允许使用不带参数的 throw 语句  
  
 不带参数的 [throw](../../csharp/language-reference/keywords/throw.md) 语句只能出现在不带任何参数的 **catch** 子句中。  
  
 有关详细信息，请参阅[异常处理语句](../../csharp/language-reference/keywords/exception-handling-statements.md)和[异常和异常处理](../../csharp/programming-guide/exceptions/index.md)。  
  
 下面的示例生成 CS0156：  
  
```csharp  
// CS0156.cs  
using System;  
  
namespace MyNamespace  
{  
   public class MyClass2 : Exception  
   {  
   }  
  
   public class MyClass  
   {  
      public static void Main()  
      {  
         try  
         {  
            throw;   // CS0156  
         }  
  
         catch(MyClass2)  
         {  
            throw;   // this throw is valid  
         }  
      }  
   }  
}  
```
