---
title: "&#39;Catch &#39;不能出现后 &#39;最后 &#39;在 &#39;请尝试 &#39;语句"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords: BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
caps.latest.revision: "8"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: b9638f930b411599ec1a9685409ff2430221f31f
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>&#39;Catch &#39;不能出现后 &#39;最后 &#39;在 &#39;请尝试 &#39;语句
`Catch` 语句出现在代码中结束 `Finally` 语句块的 `Try` 之后。 `Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。  
  
 **错误 ID：** BC30379  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1.  将 `Catch` 语句移到代码中更合适的位置。  
  
## <a name="see-also"></a>另请参阅  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [结构化的异常处理 Visual Basic 的概述](http://msdn.microsoft.com/en-us/bb81af80-a735-4873-9711-6151a48e418a)
