---
title: "&#39;Catch &#39;块永远不会达到;&lt;异常&gt;相同 &#39; 在处理上面请尝试 &#39;语句"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-visual-basic
ms.topic: article
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords: BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
caps.latest.revision: "10"
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: 201e28222be27e8ffec39bd27f525a5036ba13f4
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 11/21/2017
---
# <a name="39catch39-block-never-reached-ltexceptiongt-handled-above-in-the-same-39try39-statement"></a>&#39;Catch &#39;块永远不会达到;&lt;异常&gt;相同 &#39; 在处理上面请尝试 &#39;语句
无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。  
  
 默认情况下，此消息是一个警告。 有关隐藏警告或将警告视为错误的详细信息，请参阅[在 Visual Basic 中的配置警告](/visualstudio/ide/configuring-warnings-in-visual-basic)  
  
 **错误 ID：** BC42031  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
-   删除多余的语句。  
  
## <a name="see-also"></a>另请参阅  
 [如何： 在 Visual Basic 中捕获异常](http://msdn.microsoft.com/en-us/f3063c89-d2bf-49b1-91b5-b87edfb18b95)  
 [如何： 测试具有 Try 代码...在 Visual Basic 中 catch 块](http://msdn.microsoft.com/en-us/8368e205-ed73-4185-a247-af84fb4fafa9)  
 [如何： 筛选在 Visual Basic 中的 Catch 块中的错误](http://msdn.microsoft.com/en-us/85964d0a-56e7-4301-a96e-5eaea23b7b9b)  
 [演练： 结构化异常处理 (Visual Basic)](http://msdn.microsoft.com/en-us/440da655-4b32-490b-8b16-bfe46f41fa76)  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
